# Generated by Django 5.1.1 on 2024-09-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
                ('designation', models.CharField(max_length=100, null=True)),
                ('career_summary', models.TextField(max_length=400, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('contact_no', models.CharField(max_length=30, null=True)),
                ('linkedin_url', models.URLField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=40, null=True)),
            ],
        ),
    ]
