# Generated by Django 5.1.1 on 2024-09-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_skill_proficiency_skillname_skill_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillname',
            name='skill_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
