# Generated by Django 5.1.1 on 2024-09-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_skillname_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill_proficiency',
            name='proficiency',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=100, null=True),
        ),
    ]
