# Generated by Django 5.1.1 on 2024-09-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_resume_model_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_model',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='Media/Profile_Pic'),
        ),
    ]
