# Generated by Django 5.1.1 on 2024-09-27 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_skill_proficiency_proficiency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill_proficiency',
            old_name='proficiency',
            new_name='proficiency_level',
        ),
    ]
