# Generated by Django 5.1.1 on 2024-09-27 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_rename_proficiency_skill_proficiency_proficiency_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillname',
            old_name='skill_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='skill_model',
            name='proficiency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.skill_proficiency'),
        ),
        migrations.AlterField(
            model_name='skill_model',
            name='skill_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.skillname'),
        ),
        migrations.AlterUniqueTogether(
            name='skill_model',
            unique_together={('user', 'skill_name')},
        ),
    ]
